# Step #1
# Name the node stage "builder"
FROM node:18.16.1 AS builder
# Set working directory
WORKDIR /app
# Copy the rest of the files
COPY ./ /app/
# IMPORTANT: Copy your local node_modules directory to the container
COPY ./node_modules /app/node_modules
RUN chmod -R 777 /app/node_modules
# Run build command. No need for npm install since we're copying node_modules directly.

# Install esbuild manually
RUN npm install @esbuild/linux-x64 --legacy-peer-deps

RUN npm run build 

# nginx state for serving content
FROM nginx:alpine
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets from builder stage
COPY --from=builder /app/dist/daxa .
#Configuración de zona horaria del contenedor
RUN apk add --no-cache tzdata
ENV TZ=America/Guayaquil
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#Copiar archivo de configuracion
COPY default.conf /etc/nginx/conf.d/default.conf
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]

