# Maven 
FROM maven:3.8.1-openjdk-17-slim AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn -e -B dependency:resolve

COPY src ./src

RUN mvn clean -e -B package


# RTSDK Java
FROM openjdk:17

WORKDIR /app

ENV TZ=America/Guayaquil
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=builder /app/target/codigo-municipal-0.0.1-SNAPSHOT.jar .

EXPOSE 8282

CMD ["java", "-jar", "./codigo-municipal-0.0.1-SNAPSHOT.jar"]
